config/routes.rb
Rails.application.routes.draw do

  resources :groups

  root "groups#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord

  def private_or_public
    return "Public" if is_private == "Y"
    return "Private" if is_private == "N"
    "Unknown"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:show]

  # GET /groups
  # GET /groups.json
  def index
    @groups = Group.all
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(group_params)

    respond_to do |format|
      if @group.save
        format.html { redirect_to @group, notice: 'Group was successfully created.' }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def group_params
      params.require(:group).permit(:name, :balance, :is_private)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_embed_code.erb
<div class='embed_area'>
  <h4>
    <label for='embed_text'>HTML Embed Code</label>
  </h4>
  <textarea rows='6' cols="45"><%= "<div><script type='text/javascript' charset='utf-8'> var iframe = document.createElement('iframe');document.body.appendChild(iframe); iframe.src =".html_safe + "'#{group_url}';".html_safe + "iframe.width='300rem;';iframe.height = '75rem;';</script></div>".html_safe %>

  </textarea>
  <h4>
    <label for='embed_text'>HTML Output:</label>
  </h4>
  <section>
    <iframe src=<%="#{group_url}"%> width='300rem' height='75rem'></iframe>
  </section>
</div>

app/views/groups/_form.html.erb
<%= form_for(group) do |f| %>
  <% if group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
      <% group.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :balance %>
    <%= f.text_field :balance %>
  </div>

  <div class="field">
    <%= f.label :is_private %>
    <%= f.text_field :is_private %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/groups/edit.html.erb
<h1>Editing Group</h1>

<%= render 'form', group: @group %>

<%= link_to 'Show', @group %> |
<%= link_to 'Back', groups_path %>

app/views/groups/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="ui dividing header">Groups</h2>

<div class="ui accordion">
  <% @groups.each do |group| %>
    <div class="ui raised very padded text container segment">
      <div class="title">
        <h2 class="ui header"><%= group.name %></h2>
        <i class="dropdown icon"></i>
        Click to see details:
      </div>
      <div class="content">
        <p><strong><%= group.private_or_public %></strong></p>
        <p><strong>Balance: </strong><%= number_to_currency(group.balance)%></p>
        <%= render partial: "groups/embed_code", locals: {group_id: group.id, group_url: group_url(group.id)} %>
      </div>
    </div>
  <% end %>
</div>

app/views/groups/new.html.erb
<h1>New Group</h1>

<%= render 'form', group: @group %>

<%= link_to 'Back', groups_path %>

app/views/groups/show.html.erb
<% if notice.present? %>
  <p id="notice"><%= notice %></p>
<% end %>
<p><strong>Name: </strong><%= @group.name %></p>
<p><strong>Balance: </strong><%= number_to_currency(@group.balance)%></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GroupSnippetCreator</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>